name: CustomLoot
version: '${project.version}'
main: customloot.customloot.CustomLoot
api-version: 1.18
authors: [ Duffie13 ]
description: A plugin that adds custom loot to your minecraft server
commands:
  OpenLootMenu:
    permission: op
    usage: /openLootMenu
